### PR TITLE
adds cmake install prefix; tests for existence of mlir-opt

### PR DESCRIPTION
**Pull request by kaushikcfd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
`mlir-opt` is supposed to be an internal thing and is not installed.

**Comment by kaushikcfd** [comment]
I think we can expose it though right? For ex. `llc` one of the binaries generated during LLVM's install is copied to the environment's `bin/`

**Comment by kaushikcfd** [comment]
> I think we can expose it though right?

If yes, do we do it by adding the `cp` commands in `install_mlir.sh`?

**Comment by isuruf** [comment]
Isn't `mlir-opt` a testing tool for mlir?

**Comment by kaushikcfd** [comment]
It's like llvm's [`opt`](https://llvm.org/docs/CommandGuide/opt.html) i.e. helps calling transformation and analysis passes on the file.

**Comment by kaushikcfd** [comment]
@isuruf: How does this look?

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
