### PR TITLE
bump to 16.0.0.rc2

### PR DESCRIPTION
**Pull request by h-vetinari**

### CODE REVIEW

**Comment by makslevental** [comment]
@h-vetinari Sorry for the noob question but is there anyway to `conda install` from this (the `rc`) branch?

**Comment by h-vetinari** [comment]
> @h-vetinari Sorry for the noob question but is there anyway to `conda install` from this (the `rc`) branch?

No worries. You should be able to install it like:
```
conda install mlir -c conda-forge/label/llvm_rc -c conda-forge
```

**Comment by h-vetinari** [comment]
You'll still have to wait for the builds after the merge to finish though (and make it through the CDN). Give it another ~3h (especially as the CI didn't trigger after merging #32, so there aren't even builds for rc1).

**Comment by makslevental** [comment]
> > @h-vetinari Sorry for the noob question but is there anyway to `conda install` from this (the `rc`) branch?
> 
> No worries. You should be able to install it like:
> 
> ```
> conda install mlir -c conda-forge/label/llvm_rc -c conda-forge
> ```

ahh I tried `conda-forge/label/mlir_rc` because I saw that string somewhere in one of the CI test logs. 

>You'll still have to wait for the builds after the merge to finish though (and make it through the CDN). Give it another ~3h (especially as the CI didn't trigger after merging https://github.com/conda-forge/mlir-feedstock/pull/32, so there aren't even builds for rc1).

okay cool I'll give it a try tomorrow morning. 

Anyway god bless you for putting this together - until now I've been relying on my own [release builds of LLVM](https://github.com/makslevental/llvm-releases) purely to get precompiled MLIR (and as you can surmise from the `Actions` tab, it's been brutal getting everything lined up).

**Comment by h-vetinari** [comment]
> ahh I tried `conda-forge/label/mlir_rc` because I saw that string somewhere in one of the CI test logs.

You're right actually, you'll _also_ have to add `-c conda-forge/label/mlir_rc`; I forgot that mlir uses a different label than the rest of the LLVM rc's.



> Anyway god bless you for putting this together - until now I've been relying on my own [release builds of LLVM](https://github.com/makslevental/llvm-releases) purely to get precompiled MLIR (and as you can surmise from the `Actions` tab, it's been brutal getting everything lined up).

This feedstock was mostly the work of @isuruf & @xhochy, but happy to help. LLVM is a big baby 😅

**Comment by makslevental** [comment]
@h-vetinari no dice; I've tried a couple of different permutations of this

```
loopy) mlevental@maksims-MacBook-Pro py311 % conda install mlir -c conda-forge/label/llvm_rc -c conda-forge/label/mlir_rc -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/mlevental/miniforge3/envs/loopy

  added / updated specs:
    - mlir


The following NEW packages will be INSTALLED:

  llvm-tools         conda-forge/osx-arm64::llvm-tools-15.0.7-h62b9111_0 
  llvmdev            conda-forge/osx-arm64::llvmdev-15.0.7-h62b9111_0 
  mlir               conda-forge/osx-arm64::mlir-15.0.7-hcb86549_0 
```

and I always get 15.0.7

**Comment by h-vetinari** [comment]
I don't see how you can get the correct llvmdev dependency without also specifying `-c conda-forge/label/llvm_rc`. Normally the quotes shouldn't be necessary. In any case, happy to hear you're making progress

**Comment by makslevental** [comment]
> I don't see how you can get the correct llvmdev dependency without also specifying `-c conda-forge/label/llvm_rc`. Normally the quotes shouldn't be necessary. In any case, happy to hear you're making progress

You're correct that indeed I did need to include that channel as well - sorry I emphasized the wrong thing in that reply - I meant to put emphasis on `mlir=16` because prior I was having trouble getting conda to see the 16.0.0.rc2 release and not the ~14.0 release.

**Pull request merged**
